name: update-demo-daily
on:
  schedule:
    #- cron: "0 6 * * *" # every day at 6am
    - cron: "*/2 * * * *" # every 2 minutes
  push:
    tags:
      - "refresh-github-page" # to manually trigger a refresh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare-page
        run: |
          FEEDS="$(cat feeds.txt)"
          wget -q -O tinyfeed https://github.com/TheBigRoomXXL/tinyfeed/releases/latest/download/tinyfeed_linux_arm64
          chmod +x tinyfeed
          mkdir www
          echo $FEEDS | ./tinyfeed > ./www/index.html
          cp www/index.html www/404.html
        # 404.html allows every path to be served by the index.html

      - name: upload-page
        uses: actions/upload-pages-artifact@v3
        with:
          path: www/

  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy-to-github-pages
        id: deployment
        uses: actions/deploy-pages@v4
